#!/bin/bash

# Copied from admin-utilities/updatehtml
# Edited by @pdmosses

# run `cd docs & ./updatehtml D X` where D contains all the required *.X files

# # run from ~/TypeTopology/source

# set -euxo pipefail

# # Generate html files and deploy them.
# # This is to be run from TypeTopology/source.
# # It assumes that we want to deploy the html pages at ~/martinescardo.github.io/.

# rm -rf html
# agda --highlight-occurrences --html AllModulesIndex.lagda
# rm -f ~/martinescardo.github.io/agda/*.html # do not delete Agda.css, as it is a modified version
# mv html/*.html ~/martinescardo.github.io/agda/

# Now create copies for files that have been moved to other places
# but are linked from published papers, blogs etc.
# Symbolic links don't work any more, so we replace "ln -s" by "cp -a"

# cd ~/martinescardo.github.io/agda

cd ../$1

cp -a Higgs.index.$2 UF.HiggsInvolutionTheorem.$2
cp -a CantorSchroederBernstein.CSB.$2 CantorSchroederBernstein.$2
cp -a CoNaturals.index.$2 CoNaturals.$2
cp -a DomainTheory.ScottModelOfPCF.ScottModelOfPCF.$2 PCFModules.$2
cp -a Factorial.Law.$2 UF-Factorial.$2
cp -a Fin.ArithmeticViaEquivalence.$2 ArithmeticViaEquivalence.$2
cp -a Fin.Type.$2 Fin.$2
cp -a Fin.UniverseInvariance.$2 UF-Finiteness-Universe-Invariance.$2
cp -a Fin.index.$2 Fin-Properties.$2
cp -a Games.FiniteHistoryDependent.$2 FiniteHistoryDependentGames.$2
cp -a Groups.Free.$2 FreeGroup.$2
cp -a Groups.Free.$2 FreeGroupOfLargeLocallySmallSet.$2
cp -a InjectiveTypes.index.$2 InjectiveTypes.$2
cp -a Locales.AdjointFunctorTheoremForFrames.$2 AdjointFunctorTheoremForFrames.$2
cp -a Locales.CompactRegular.$2 CompactRegular.$2
cp -a Locales.Frame.$2 Frame.$2
cp -a Locales.PosetalAdjunction.$2 GaloisConnection.$2
cp -a Locales.HeytingImplication.$2 HeytingImplication.$2
cp -a NotionsOfDecidability.SemiDecidable.$2 SemiDecidable.$2
cp -a Ordinals.AdditionProperties.$2 OrdinalArithmetic-Properties.$2
cp -a Ordinals.BuraliForti.$2 BuraliForti.$2
cp -a Ordinals.Notions.$2 Ordinal-Notions.$2
cp -a Ordinals.OrdinalOfOrdinals.$2 OrdinalOfOrdinals.$2
cp -a Ordinals.WellOrderTransport.$2 OrdinalsWellOrderTransport.$2
cp -a Ordinals.index.$2 Ordinals.$2
cp -a Slice.Construction.$2 Slice.$2
cp -a TypeTopology.ADecidableQuantificationOverTheNaturals.$2 ADecidableQuantificationOverTheNaturals.$2
cp -a TypeTopology.GenericConvergentSequenceCompactness.$2 ConvergentSequenceCompactness.$2
cp -a TypeTopology.GenericConvergentSequenceCompactness.$2 ConvergentSequenceSearchable.$2
cp -a TypeTopology.RicesTheoremForTheUniverse.$2 RicesTheoremForTheUniverse.$2
cp -a TypeTopology.TheTopologyOfTheUniverse.$2 TheTopologyOfTheUniverse.$2
cp -a UF.Choice.$2 UF-Choice.$2
cp -a UF.DiscreteAndSeparated.$2 DiscreteAndSeparated.$2
cp -a UF.HiggsInvolutionTheorem.$2 Various.HiggsInvolutionTheorem.$2
cp -a UF.Size.$2 UF-Size.$2
cp -a UF.UniverseEmbedding.$2 UniverseEmbedding.$2
cp -a UF.Yoneda.$2 UF-Yoneda.$2
cp -a UF.index.$2 UF.$2
cp -a Various.Dedekind.$2 Dedekind.$2
cp -a Various.HiggsInvolutionTheorem.$2 HiggsInvolutionTheorem.$2
cp -a Various.LawvereFPT.$2 LawvereFPT.$2
cp -a Various.Types2019.$2 Types2019.$2
cp -a Various.UnivalenceFromScratch.$2 UnivalenceFromScratch.$2

# From now on (12th Jan 2023), published things should go to
# ~/martinescardo.github.io/TypeTopology/Published.* Use symlinks as above to
# create them. NB. Don't use subdirectories because the links in the
# symlinked html files may break.

# These are linked to in Tom de Jong's PhD thesis (2022) and duplicates some of
# the above for consistency.
cp -a DomainTheory.index.$2 Published.DomainTheory.index.$2
cp -a DomainTheory.Bilimits.Dinfinity.$2 Published.DomainTheory.Bilimits.Dinfinity.$2
cp -a DomainTheory.ScottModelOfPCF.ScottModelOfPCF.$2 Published.DomainTheory.ScottModelOfPCF.ScottModelOfPCF.$2
cp -a Lifting.IdentityViaSIP.$2 Published.Lifting.IdentityViaSIP.$2
cp -a NotionsOfDecidability.SemiDecidable.$2 Published.NotionsOfDecidability.SemiDecidable.$2
cp -a Slice.Construction.$2 Published.Slice.Slice.$2
cp -a Ordinals.BuraliForti.$2 Published.Ordinals.BuraliForti.$2
cp -a Ordinals.OrdinalOfOrdinals.$2 Published.Ordinals.OrdinalOfOrdinals.$2
cp -a Ordinals.OrdinalOfOrdinalsSuprema.$2 Published.Ordinals.OrdinalOfOrdinalsSuprema.$2
cp -a Ordinals.Type.$2 Published.Ordinals.Type.$2
cp -a TypeTopology.CompactTypes.$2 Published.TypeTopology.CompactTypes.$2
cp -a TypeTopology.Density.$2 Published.TypeTopology.Density.$2
cp -a UF.DiscreteAndSeparated.$2 Published.TypeTopology.DiscreteAndSeparated.$2
cp -a TypeTopology.SimpleTypes.$2 Published.TypeTopology.SimpleTypes.$2
cp -a Quotient.Large-Variation.$2 Published.UF.Quotient-F.$2
cp -a Quotient.index.$2 Published.UF.Quotient.$2
cp -a Quotient.index.$2 Published.UF.Quotient-Replacement.$2
cp -a Quotient.Large.$2 Published.UF.Large-Quotient.$2
cp -a Various.Dedekind.$2 Published.Various.Dedekind.$2

# Further links using the Published.* scheme
# Added by Tom de Jong - 31 March 2023, 18 April 2023
cp -a UF.Size.$2 Published.UF.Size.$2
cp -a UF.ImageAndSurjection.$2 Published.UF.ImageAndSurjection.$2

# Added by Tom de Jong on 3 October 2023.
cp -a PCF.Lambda.index.$2 Published.PCF.Lambda.index.$2

# # git add the above files
# cd ..
# chmod a+r agda/*
# git add agda

# # Deprecated - agda-new should not be offered as a public link any more,
# # for some years now:
# rm -rf agda-new
# cp -a agda agda-new
# chmod a+r agda-new/*
# git add agda-new
