nav:
  - nav.md
  - About: 
    - about.md
    - user-guide.md
  - AllModulesIndex:
    - nav/AllModulesIndex/index.md
  - Library:
    - nav/index/index.md
    - nav/*
  - HTML: AllModulesIndex.html

preserve_directory_names: true

sort:
  sections: mixed