nav:
  - About: nav.md
  - AllModulesIndex:
    - AllModulesIndex/index.md
    - HTML: AllModulesIndex.html
  - Modules:
    - index/index.md
    - '*'

preserve_directory_names: true

sort:
  sections: mixed